# Generated by Django 4.2.17 on 2025-08-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kunden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurzbeschreibung', models.CharField(blank=True, max_length=50)),
                ('ausfuehrungsdatum', models.DateField(blank=True)),
                ('rechnungsnummer', models.CharField(blank=True, max_length=50, unique=True)),
                ('angebotsnummer', models.CharField(blank=True, max_length=50, unique=True)),
                ('notiz', models.TextField(blank=True)),
                ('summe', models.FloatField(blank=True, default=0.0)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunden.kunde')),
            ],
        ),
        migrations.CreateModel(
            name='Leistung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=255)),
                ('interne_nummer', models.CharField(max_length=50, unique=True)),
                ('preis_pro_einheit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('einheit', models.CharField(choices=[('Stk', 'Stück'), ('Pkg', 'Packung'), ('kg', 'Kilogramm'), ('m', 'Meter'), ('m²', 'Quadratmeter'), ('m³', 'Kubikmeter'), ('h', 'Stunde'), ('km', 'Kilometer')], default='h', max_length=10)),
                ('notiz', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuftragLeistung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.PositiveIntegerField()),
                ('summe', models.FloatField(blank=True, default=0.0)),
                ('auftrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auftraege.auftrag')),
                ('leistung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auftraege.leistung')),
            ],
        ),
        migrations.AddField(
            model_name='auftrag',
            name='leistungen',
            field=models.ManyToManyField(blank=True, through='auftraege.AuftragLeistung', to='auftraege.leistung'),
        ),
    ]
