# Generated by Django 4.2.17 on 2025-02-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kunden', '0002_alter_kunde_email_alter_kunde_hausnummer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausfuehrungsdatum', models.DateField()),
                ('rechnungsnummer', models.CharField(max_length=50, unique=True)),
                ('angebotsnummer', models.CharField(max_length=50, unique=True)),
                ('kurzbeschreibung', models.TextField()),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunden.kunde')),
            ],
        ),
        migrations.CreateModel(
            name='Leistung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=255)),
                ('interne_nummer', models.CharField(max_length=50, unique=True)),
                ('preis_pro_einheit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notiz', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuftragLeistung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.PositiveIntegerField()),
                ('auftrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auftraege.auftrag')),
                ('leistung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auftraege.leistung')),
            ],
        ),
        migrations.AddField(
            model_name='auftrag',
            name='leistungen',
            field=models.ManyToManyField(through='auftraege.AuftragLeistung', to='auftraege.leistung'),
        ),
    ]
