# Generated by Django 4.2.17 on 2025-02-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftraege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftrag',
            name='kurzbeschreibung',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auftrag',
            name='leistungen',
            field=models.ManyToManyField(blank=True, through='auftraege.AuftragLeistung', to='auftraege.leistung'),
        ),
    ]
