# Generated by Django 4.2.17 on 2025-02-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftraege', '0002_alter_auftrag_kurzbeschreibung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftrag',
            name='angebotsnummer',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='auftrag',
            name='ausfuehrungsdatum',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='auftrag',
            name='rechnungsnummer',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
