# Generated by Django 4.2.17 on 2025-02-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftraege', '0003_alter_auftrag_angebotsnummer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auftrag',
            name='notiz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auftrag',
            name='kurzbeschreibung',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
