# Generated by Django 4.2.17 on 2025-02-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftraege', '0004_auftrag_notiz_alter_auftrag_kurzbeschreibung'),
    ]

    operations = [
        migrations.AddField(
            model_name='auftrag',
            name='summe',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='auftragleistung',
            name='summe',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
