# Generated by Django 4.2.17 on 2025-02-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftraege', '0005_auftrag_summe_auftragleistung_summe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftrag',
            name='summe',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auftragleistung',
            name='summe',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
