# Generated by Django 4.2.17 on 2025-02-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auftraege', '0008_alter_auftrag_summe_alter_auftragleistung_summe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auftrag',
            name='summe',
        ),
    ]
