# Generated by Django 4.2.17 on 2025-02-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftraege', '0010_remove_auftragleistung_summe'),
    ]

    operations = [
        migrations.AddField(
            model_name='auftrag',
            name='summe',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='auftragleistung',
            name='summe',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
