# Generated by Django 4.2.17 on 2025-03-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftraege', '0011_auftrag_summe_auftragleistung_summe'),
    ]

    operations = [
        migrations.AddField(
            model_name='leistung',
            name='einheit',
            field=models.CharField(choices=[('Stk', 'Stück'), ('kg', 'Kilogramm'), ('m', 'Meter'), ('m²', 'Quadratmeter'), ('m³', 'Kubikmeter'), ('h', 'Stunde'), ('km', 'Kilometer')], default='h', max_length=10),
        ),
    ]
