# Generated by Django 4.2.17 on 2025-03-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auftraege', '0012_leistung_einheit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leistung',
            name='einheit',
            field=models.CharField(choices=[('Stk', 'Stück'), ('Pkg', 'Packung'), ('kg', 'Kilogramm'), ('m', 'Meter'), ('m²', 'Quadratmeter'), ('m³', 'Kubikmeter'), ('h', 'Stunde'), ('km', 'Kilometer')], default='h', max_length=10),
        ),
    ]
