# Generated by Django 4.2.17 on 2025-03-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kunden', '0002_alter_kunde_email_alter_kunde_hausnummer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=255)),
                ('preis_pro_einheit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('einheit', models.CharField(choices=[('Stk', 'Stück'), ('Pkg', 'Packung'), ('kg', 'Kilogramm'), ('m', 'Meter'), ('m²', 'Quadratmeter'), ('m³', 'Kubikmeter'), ('h', 'Stunde'), ('km', 'Kilometer')], default='Stk', max_length=10)),
                ('notiz', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kurs_ziel', models.TextField()),
                ('datum', models.DateField()),
                ('startzeit', models.TimeField()),
                ('endzeit', models.TimeField()),
                ('fremdresourcen', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopTeilnehmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmeldedatum', models.DateTimeField(auto_now_add=True, null=True)),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunden.kunde')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge', models.PositiveIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.material')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop')),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='material',
            field=models.ManyToManyField(blank=True, through='workshops.WorkshopMaterial', to='workshops.material'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='teilnehmer',
            field=models.ManyToManyField(blank=True, through='workshops.WorkshopTeilnehmer', to='kunden.kunde'),
        ),
    ]
