# Generated by Django 4.2.17 on 2025-03-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopteilnehmer',
            name='bezahlt',
            field=models.BooleanField(default=False),
        ),
    ]
