# Generated by Django 4.2.17 on 2025-02-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('ort', models.CharField(max_length=100)),
                ('strasse', models.CharField(max_length=100)),
                ('hausnummer', models.CharField(max_length=10)),
                ('plz', models.CharField(max_length=10)),
                ('auftraege', models.BooleanField(default=False)),
                ('workshops', models.BooleanField(default=False)),
            ],
        ),
    ]
