# Generated by Django 4.2.17 on 2025-08-07 20:13

from django.db import migrations, models

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='philip.pointecker@gmail.com',
            password='po'
        )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('ort', models.CharField(blank=True, max_length=100, null=True)),
                ('strasse', models.CharField(blank=True, max_length=100, null=True)),
                ('hausnummer', models.CharField(blank=True, max_length=10, null=True)),
                ('plz', models.CharField(blank=True, max_length=10, null=True)),
                ('auftraege', models.BooleanField(default=False)),
                ('workshops', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_superuser),
    ]
